import javax.swing.JFrame;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author polav
 */
public class adminHome extends javax.swing.JFrame {
public static int open=0;  
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminHome.class.getName());

    /**
     * Creates new form adminHome
     */
    public adminHome() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        getContentPane().setBackground(new java.awt.Color(240,255,255));
        jaddNQ.setBackground(new java.awt.Color(65, 94, 114));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jaddNQ = new javax.swing.JMenu();
        jupd = new javax.swing.JMenu();
        jallque = new javax.swing.JMenu();
        jdel = new javax.swing.JMenu();
        jresult = new javax.swing.JMenu();
        mlogout = new javax.swing.JMenu();
        mexit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jaddNQ.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\add-question.png")); // NOI18N
        jaddNQ.setText("Add New Question");
        jaddNQ.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        jaddNQ.setMargin(new java.awt.Insets(0, 5, 0, 30));
        jaddNQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jaddNQMouseClicked(evt);
            }
        });
        jMenuBar1.add(jaddNQ);

        jupd.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\upda_qu.png")); // NOI18N
        jupd.setText("Update Question");
        jupd.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        jupd.setMargin(new java.awt.Insets(0, 5, 0, 30));
        jupd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jupdStateChanged(evt);
            }
        });
        jupd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jupdMouseClicked(evt);
            }
        });
        jMenuBar1.add(jupd);

        jallque.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\all_q.png")); // NOI18N
        jallque.setText("ALl Questions");
        jallque.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        jallque.setMargin(new java.awt.Insets(0, 5, 0, 30));
        jallque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jallqueMouseClicked(evt);
            }
        });
        jMenuBar1.add(jallque);

        jdel.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\bin1.png")); // NOI18N
        jdel.setText("Delete Question");
        jdel.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        jdel.setMargin(new java.awt.Insets(0, 5, 0, 30));
        jdel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdelMouseClicked(evt);
            }
        });
        jMenuBar1.add(jdel);

        jresult.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\R_kee.png")); // NOI18N
        jresult.setText("User Result");
        jresult.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        jresult.setMargin(new java.awt.Insets(0, 5, 0, 30));
        jresult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jresultMouseClicked(evt);
            }
        });
        jMenuBar1.add(jresult);

        mlogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\l_kee.png")); // NOI18N
        mlogout.setText("Logout");
        mlogout.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        mlogout.setMargin(new java.awt.Insets(0, 5, 0, 30));
        mlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mlogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(mlogout);

        mexit.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\wrong.png")); // NOI18N
        mexit.setText("Exit");
        mexit.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        mexit.setMargin(new java.awt.Insets(0, 5, 0, 30));
        mexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mexitMouseClicked(evt);
            }
        });
        jMenuBar1.add(mexit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1208, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mlogoutMouseClicked
        JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(jf,"Do you really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new loginAdmin().setVisible(true);
        }
    }//GEN-LAST:event_mlogoutMouseClicked

    private void mexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mexitMouseClicked
        JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(jf,"Do you really want to Exit Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_mexitMouseClicked

    private void jaddNQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jaddNQMouseClicked
       
        if(open==0)
        {
            new addNewQuestion().setVisible(true);
            open=1;
        }
        else
        {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"One form is already Open");
        }
    }//GEN-LAST:event_jaddNQMouseClicked

    private void jupdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jupdStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jupdStateChanged

    private void jupdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jupdMouseClicked
        if(open==0)
        {
            new updateQuestion().setVisible(true);
            open=1;
        }
        else
        {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"One form is already Open");
        }
    }//GEN-LAST:event_jupdMouseClicked

    private void jallqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jallqueMouseClicked
        if(open==0)
        {
            new allQuestion().setVisible(true);
            open=1;
        }
        else
        {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"One form is already Open");
        }
    }//GEN-LAST:event_jallqueMouseClicked

    private void jdelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdelMouseClicked
        if(open==0)
        {
            new delQuestion().setVisible(true);
            open=1;
        }
        else
        {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"One form is already Open");
        }
    }//GEN-LAST:event_jdelMouseClicked

    private void jresultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jresultMouseClicked
        if(open==0)
        {
            new allStudentResult().setVisible(true);
            open=1;
        }
        else
        {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,"One form is already Open");
        }
    }//GEN-LAST:event_jresultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminHome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jaddNQ;
    private javax.swing.JMenu jallque;
    private javax.swing.JMenu jdel;
    private javax.swing.JMenu jresult;
    private javax.swing.JMenu jupd;
    private javax.swing.JMenu mexit;
    private javax.swing.JMenu mlogout;
    // End of variables declaration//GEN-END:variables
}
