
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author polav
 */
public class index extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(index.class.getName());

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        getContentPane().setBackground(new java.awt.Color(240,255,255));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The coni woulent of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        juser = new javax.swing.JButton();
        jadmin = new javax.swing.JButton();
        jcontactus = new javax.swing.JButton();
        jexit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        juser.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        juser.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\keer.png")); // NOI18N
        juser.setText("User");
        juser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juserActionPerformed(evt);
            }
        });
        getContentPane().add(juser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 146, -1));

        jadmin.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jadmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\admin.png")); // NOI18N
        jadmin.setText("Admin");
        jadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadminActionPerformed(evt);
            }
        });
        getContentPane().add(jadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        jcontactus.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jcontactus.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\contact us.png")); // NOI18N
        jcontactus.setText("Contact Us");
        jcontactus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcontactusActionPerformed(evt);
            }
        });
        getContentPane().add(jcontactus, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, -1));

        jexit.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jexit.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\wrong.png")); // NOI18N
        jexit.setText("Exit");
        jexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitActionPerformed(evt);
            }
        });
        getContentPane().add(jexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        jLabel3.setText("ONLINE QUIZ EXAM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 520, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void juserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juserActionPerformed
       setVisible(false);
       new studentDetails().setVisible(true);
    }//GEN-LAST:event_juserActionPerformed

    private void jadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadminActionPerformed
        setVisible(false);
        new loginAdmin().setVisible(true);
    }//GEN-LAST:event_jadminActionPerformed

    private void jcontactusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcontactusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcontactusActionPerformed

    private void jexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to exit application?","Select",JOptionPane.YES_NO_OPTION );
        if (a == 0) {
        System.exit(0);
    }
    }//GEN-LAST:event_jexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
   
        // Apply FlatLaf Light Theme
        
  
       
        java.awt.EventQueue.invokeLater(() -> new index().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jadmin;
    private javax.swing.JButton jcontactus;
    private javax.swing.JButton jexit;
    private javax.swing.JButton juser;
    // End of variables declaration//GEN-END:variables
}
