

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author polav
 */
public class instuctionStudent extends javax.swing.JFrame {  
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(instuctionStudent.class.getName());

    /**
     * Creates new form instuctionStudent
     */
     private int userId;

    // ✅ Constructor that requires UserId
    public instuctionStudent(int userId) {
        initComponents();
        
        this.userId = userId;
        jTextArea1.setEditable(false);
    }

    // (Optional) default constructor - only if needed elsewhere
    public instuctionStudent() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        getContentPane().setBackground(new java.awt.Color(240,255,255));
        jTextArea1.setBackground(new java.awt.Color(211, 218, 217));  // Button color
        jTextArea1.setForeground(new java.awt.Color(0,0,0));
        jstart.setBackground(new java.awt.Color(65, 94, 114));  // Button color
        jstart.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setEditable(false);
    }

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jstart = new javax.swing.JButton();
        jback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\instructionss.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 28)); // NOI18N
        jLabel2.setText("Instructions");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 200, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 2, 20)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Exam Instructions:\n\n1. You are not allowed to use textbooks, notes, mobile phones, \n   or get assistance from anyone during the exam.\n\n2. The test contains 10 multiple-choice questions and must be \n   finished within the 10-minute time limit.\n\n3. Once the exam has started, you must complete it in one sitting. \n   Do not exit or minimize, as the system may lock you out and \n   prevent you from rejoining.\n\n4. Your responses will be saved automatically. Submitting early \n   will end your session immediately.\n\nNumber of Questions: 10\nExam Duration: 10 minutes\nGood Luck!\n");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1430, 507));

        jstart.setFont(new java.awt.Font("Segoe UI Variable", 1, 30)); // NOI18N
        jstart.setText("START QUIZ");
        jstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstartActionPerformed(evt);
            }
        });
        getContentPane().add(jstart, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 676, 207, 60));

        jback.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\bacck.png")); // NOI18N
        jback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbackActionPerformed(evt);
            }
        });
        getContentPane().add(jback, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 10, 80, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbackActionPerformed
          setVisible(false);
          new studentDetails().setVisible(true);
    }//GEN-LAST:event_jbackActionPerformed

    private void jstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstartActionPerformed
        setVisible(false);
        new quizExamStudent(userId).setVisible(true);
    }//GEN-LAST:event_jstartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new instuctionStudent().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jback;
    private javax.swing.JButton jstart;
    // End of variables declaration//GEN-END:variables
}
