import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author polav
 */
public class loginAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loginAdmin.class.getName());

    /**
     * Creates new form loginAdmin
     */
    public loginAdmin() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        getContentPane().setBackground(new java.awt.Color(240,255,255));
        // Change button background and text color
        jlogin.setBackground(new java.awt.Color(65, 94, 114));  // Button color
        jlogin.setForeground(new java.awt.Color(255, 255, 255)); // Text color



        jexit.setBackground(new java.awt.Color(65, 94, 114));  // Red exit button
        jexit.setForeground(new java.awt.Color(255, 255, 255));
// light blue
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        juser = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        jexit = new javax.swing.JButton();
        jlogin = new javax.swing.JButton();
        jshow = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(java.awt.Color.cyan);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 28)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\admin.png")); // NOI18N
        jLabel1.setText("ADMIN LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 270, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel2.setText("UserName");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 130, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel3.setText("Passsword");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 110, 40));
        getContentPane().add(juser, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 210, 40));
        getContentPane().add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 210, 40));

        jexit.setBackground(new java.awt.Color(0, 0, 102));
        jexit.setFont(new java.awt.Font("Segoe UI Semibold", 3, 20)); // NOI18N
        jexit.setForeground(new java.awt.Color(255, 255, 255));
        jexit.setText("Exit");
        jexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitActionPerformed(evt);
            }
        });
        getContentPane().add(jexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 90, 40));

        jlogin.setBackground(new java.awt.Color(0, 0, 102));
        jlogin.setFont(new java.awt.Font("Segoe UI Semibold", 3, 20)); // NOI18N
        jlogin.setForeground(new java.awt.Color(255, 255, 255));
        jlogin.setText("Login");
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });
        getContentPane().add(jlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 90, 40));

        jshow.setText("Show Password");
        jshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jshowActionPerformed(evt);
            }
        });
        getContentPane().add(jshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
        if(juser.getText().equals(""))
         {
             JOptionPane.showMessageDialog(null,"Please enter the Username");
         }
          else if(jpassword.getText().equals(""))
         {
             JOptionPane.showMessageDialog(null,"Please enter the Password");
         }
        else if(juser.getText().equals("Keerthi") && jpassword.getText().equals("12345"))
         {
             setVisible(false);
             new adminHome().setVisible(true);
         }
         else
         {
             JOptionPane.showMessageDialog(null,"Wrong Username or Password");
         }
    }//GEN-LAST:event_jloginActionPerformed

    private void jexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitActionPerformed
         setVisible(false);
         new index().setVisible(true);
    }//GEN-LAST:event_jexitActionPerformed

    private void jshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jshowActionPerformed
        if(jshow.isSelected())
        {
            jpassword.setEchoChar((char)0);
        }
        else
        {
            jpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jshowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new loginAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jexit;
    private javax.swing.JButton jlogin;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JCheckBox jshow;
    private javax.swing.JTextField juser;
    // End of variables declaration//GEN-END:variables
}
