import java.sql.*;

import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author polav
 */
public class studentDetails extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(studentDetails.class.getName());

    /**
     * Creates new form studentDetails
     */
    public studentDetails() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(240,255,255));
        jsave.setBackground(new java.awt.Color(65, 94, 114));  // Button color
        jsave.setForeground(new java.awt.Color(255, 255, 255));
         setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        

        txtName.requestFocusInWindow();
        jTextArea1.setEditable(false);
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        jdatef.setText(dFormat.format(date));
        // Add instructions text
        jTextArea1.setText(
    "Instructions:\n"
  + "1. Please fill all details carefully.\n"
  + "2. Enter a valid Email (example: user@gmail.com).\n"
  + "3. Contact number must be exactly 10 digits.\n"
  + "4. Name and Surname should only contain alphabets.\n"
  + "5. After filling details, click 'Save & Next' to continue."      
     );
       jsave.setEnabled(false);  
       jCheckBox1.addActionListener(evt -> {
        if (jCheckBox1.isSelected()) {
            jsave.setEnabled(true);   // enable
        } else {
            jsave.setEnabled(false);  // disable
        }
    });

        
    }
    
    private boolean isValidEmail(String email) {
    String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
    return email.matches(emailRegex);
}

    private boolean isValidContact(String contact) {
    String contactRegex = "^[0-9]{10}$"; // exactly 10 digits
    return contact.matches(contactRegex);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jback = new javax.swing.JButton();
        jexit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jsave = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jdatef = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\user.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, -1, 73));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 28)); // NOI18N
        jLabel2.setText("Fill The Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 32, 206, 39));

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\calendarr.png")); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 120, 39));

        jback.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jback.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\bacck.png")); // NOI18N
        jback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbackActionPerformed(evt);
            }
        });
        getContentPane().add(jback, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, 80, 70));

        jexit.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\wrong.png")); // NOI18N
        jexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitActionPerformed(evt);
            }
        });
        getContentPane().add(jexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 1420, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel5.setText("Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 79, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel6.setText("SurName");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel7.setText("Gender");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 79, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel8.setText("E-Mail");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 79, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel9.setText("Contact No");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        txtName.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 292, -1));

        txtSurname.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        getContentPane().add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 292, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 292, -1));

        txtContact.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        getContentPane().add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 292, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 1035, -1));
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, 31));

        jsave.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jsave.setForeground(new java.awt.Color(51, 51, 0));
        jsave.setIcon(new javax.swing.ImageIcon("C:\\Users\\polav\\OneDrive\\Pictures\\Whatsapp\\nextt.png")); // NOI18N
        jsave.setText("Save & Next");
        jsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaveActionPerformed(evt);
            }
        });
        getContentPane().add(jsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, 220, 60));

        jComboBox1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 292, -1));

        jdatef.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        getContentPane().add(jdatef, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbackActionPerformed
        setVisible(false);
        new index().setVisible(true);
    }//GEN-LAST:event_jbackActionPerformed

    private void jexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to exit application?","Select",JOptionPane.YES_NO_OPTION );
        if (a == 0) {
        System.exit(0);
    }
    }//GEN-LAST:event_jexitActionPerformed

    private void jsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaveActionPerformed
         if (!jCheckBox1.isSelected()) {
        JOptionPane.showMessageDialog(this,
            "Please read and agree to the instructions before proceeding!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return; // stop execution
         }
        
        String Name = txtName.getText();
        String SurName = txtSurname.getText();
        String Gender = (String)jComboBox1.getSelectedItem();
        String EMail = txtEmail.getText();
        String ContactNo= txtContact.getText();
        String Marks="0";
        
        
        if (Name.isEmpty() || SurName.isEmpty() || EMail.isEmpty() || ContactNo.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "All fields must be filled before saving!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
        }
         if (!Name.matches("^[A-Za-z]+$")) {
        JOptionPane.showMessageDialog(this, "Name should contain only alphabets!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        if (!SurName.matches("^[A-Za-z]+$")) {
        JOptionPane.showMessageDialog(this, "Surname should contain only alphabets!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
         if (!isValidEmail(EMail)) {
        JOptionPane.showMessageDialog(this, "Invalid Email Address!", "Error", JOptionPane.ERROR_MESSAGE);
        return; // stop execution
        }

        if (!isValidContact(ContactNo)) {
        JOptionPane.showMessageDialog(this, "Invalid Contact Number! Must be 10 digits.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // stop execution
        }
        try {
    Connection con = ConnectionProvider.getCon();

    PreparedStatement ps = con.prepareStatement(
        "INSERT INTO user(Name, SurName, Gender, EMail, ContactNo, Marks) VALUES(?,?,?,?,?,?)",
        Statement.RETURN_GENERATED_KEYS
    );

    ps.setString(1, Name);
    ps.setString(2, SurName);
    ps.setString(3, Gender);
    ps.setString(4, EMail);
    ps.setString(5, ContactNo);
    ps.setString(6, Marks);

    ps.executeUpdate();

    // ✅ Get the auto-generated UserId
    ResultSet rs = ps.getGeneratedKeys();
    if (rs.next()) {
        int newUserId = rs.getInt(1);  // fetch auto id from DB

        JOptionPane.showMessageDialog(
            this,
            "Saved Successfully!\nYour User ID is: " + newUserId,
            "Success",
            JOptionPane.INFORMATION_MESSAGE
        );

        // ✅ Pass UserId to instuctionStudent frame
        setVisible(false);
        new instuctionStudent(newUserId).setVisible(true);
    }

    // ✅ Clear fields after saving
    txtName.setText("");
    txtSurname.setText("");
    txtEmail.setText("");
    txtContact.setText("");
    jCheckBox1.setSelected(false);
    jsave.setEnabled(false);

} catch (Exception e) {
    JOptionPane.showMessageDialog(
        null,
        "Error: " + e.getMessage(),
        "Database Error",
        JOptionPane.ERROR_MESSAGE
    );
}



        
        
    }//GEN-LAST:event_jsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new studentDetails().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jback;
    private javax.swing.JTextField jdatef;
    private javax.swing.JButton jexit;
    private javax.swing.JButton jsave;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}

